# 图像的读取

In [2]:
import cv2 #opencv读取的是BGR的格式
import matplotlib.pyplot as plt #matplotlib是RGB格式
import numpy as np
%matplotlib inline

img = cv2.imread("WechatIMG7.jpg")

In [5]:
img

array([[[ 4, 29, 33],
        [ 4, 29, 33],
        [ 4, 29, 33],
        ...,
        [ 6, 27, 29],
        [ 6, 27, 29],
        [ 6, 27, 29]],

       [[ 4, 29, 33],
        [ 4, 29, 33],
        [ 4, 29, 33],
        ...,
        [ 6, 27, 29],
        [ 6, 27, 29],
        [ 6, 27, 29]],

       [[ 4, 29, 33],
        [ 4, 29, 33],
        [ 4, 29, 33],
        ...,
        [ 6, 27, 29],
        [ 6, 27, 29],
        [ 6, 27, 29]],

       ...,

       [[ 3, 36, 32],
        [ 3, 36, 32],
        [ 3, 36, 32],
        ...,
        [ 7, 36, 33],
        [ 7, 36, 33],
        [ 7, 36, 33]],

       [[ 3, 36, 32],
        [ 3, 36, 32],
        [ 3, 36, 32],
        ...,
        [ 7, 36, 33],
        [ 7, 36, 33],
        [ 7, 36, 33]],

       [[ 3, 36, 32],
        [ 3, 36, 32],
        [ 3, 36, 32],
        ...,
        [ 7, 36, 33],
        [ 7, 36, 33],
        [ 7, 36, 33]]], dtype=uint8)

In [3]:
cv2.imshow("image",img) #图像的显示，创建一个窗口用来显示上述的图像
cv2.waitKey(0) #等待时间，0表示一直显示，毫秒级
cv2.destroyAllWindows()

In [2]:
def cv_show(name,img):
    cv2.imshow(name,img)
    cv2.waitKey(10)
    cv2.destroyALLWindows()

In [6]:
img.shape #(hwc) h代表图片的高，w代表图片的宽，c代表图像的通道数，c=3说明图像是RGB三色的，但是在opencv中使用BGR格式的

(956, 954, 3)

In [2]:
img = cv2.imread('WechatIMG8.jpg',cv2.IMREAD_GRAYSCALE)
#cv2.IMREAD_COLOR代表的是读进彩色图像，
#cv2.IMREAD_GRAYSCALE代表读进灰度图像
img

array([[54, 54, 54, ...,  1,  1,  1],
       [53, 53, 54, ...,  1,  1,  1],
       [53, 53, 54, ...,  1,  1,  1],
       ...,
       [35, 34, 34, ..., 67, 67, 67],
       [31, 30, 30, ..., 68, 68, 68],
       [40, 40, 40, ..., 68, 67, 67]], dtype=uint8)

In [3]:
img.shape

(605, 591)

In [4]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
#保存
cv2.imwrite('mycat.png',img)

True

In [4]:
type(img)

numpy.ndarray

In [5]:
img.size

357555

In [6]:
img.dtype

dtype('uint8')

# 视频的读取
cv2.VideoCapture用来捕获摄像头的画面，用数字来控制不同的设备，例如1，0
如果是视频的话，直接指定好路径就行

In [ ]:
import cv2                    #opencv读取的是BGR的格式

vc = cv2.VideoCapture('caochang.mp4')

In [ ]:
if vc.isOpened():
    open ，frame = vc.read()           #vc.read返回两个变量，open是个标志说明能被打开，frame接受vc变量中的一帧视频图像
else:
    open = False

In [ ]:
while open:
    ret，frame = vc.read()        # frame接受vc变量中的一帧视频图像
    if frame is None:        #当循环到视频的末尾没有新的帧就自动退出
        break
    if ret == True:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  #cv2.COLOR_BGR2GRAY用来将三色视频图像转换成灰度图像
        cv2.imshow('result',gray)
        if cv2.waitKey(100) & 0xFF ==27: #27代表的是退出健，没有什么特殊意义
            break
vc.release()
cv2.destroyALLWindows()
        

# 截取部分图像数据

In [10]:
import cv2
def cv_show(name,img):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyALLWindows()

In [ ]:
img = cv2.imread('WechatIMG9.jpg')
cat = img[0:50,0:200]
cv_show('cat',cat)

In [9]:
img = cv2.imread('WechatIMG9.jpg')
b,g,r = cv2.split(img)
print(b)

[[ 20  21  21 ...   9  10  10]
 [ 21  21  22 ...  13  15  16]
 [ 22  22  23 ...  18  17  20]
 ...
 [178 178 178 ...  10  11  11]
 [178 178 178 ...  11  11  12]
 [178 178 178 ...  10  11  11]]


In [ ]:
#只保留单通道图像

cur_img = img.copy()
cur_img[:,:,0] = 0
cur_img[:,:,1] = 0
cv_show('r',cur_img)

# 边界填充

In [2]:
#复制法，直接复制最边缘的像素 BORDER_REPLCATE
#反射法，对图像中的像素在两边进行复制 BORDER_REFLECT          复制像素时包括最边缘的像素进行复制
#反射法，以最边缘的像素为轴进行对称生成边界 BORDER_REFLECT_101 复制像素时不包括最边缘的像素进行复制
#外包装法 BORDER_WRAP                                    复制图像时用同样的像素顺序进行复制
# 常量法 ，用常数值进行填充 BORDER_CONSTANT

# 图像数值计算

In [ ]:
import cv2
img_add1 = cv2.imread('WechatIMG8.jpg')
img_add2 = img_add1 + 10     #给图像的每一个通道都增加数值10
img_add1          #显示图像的b通道
cv2.imshow('img',img_add1[:,:,0])

img_add2
cv2.imshow('img2',img_add2[:,:,0])
cv2.waitKey(0)
cv2.destroyAllWindows()